Tensorflow与Keras的最大区别是，Tensorflow必须自行设计张量运算

Tensorflow程序设计的核心是“计算图”，可分为建立计算图和执行计算图两部分

（1）建立计算图

我们可以使用Tensorflow提供的模块建立计算图。Tensorflow提供的模块非常强大，我们可以自行设计张量运算流程，并且构建各种深度学习和机器学习模型

（2）执行计算图

建立好计算图后，我们就可以建立Session执行计算图。在Tensorflow中，Session（原意是会话）的作用是在客户端和执行设备间建立连接。有了这个连接，就可以将计算图在不同设备中执行，后续任何与设备之间的数据传输必须通过Session才能进行，执行计算图后会返回结果

# 建立计算图

本节建立简单的计算图，只有一个常数和一个变量，建立完成后再执行此计算图

导入Tensorflow模块

In [1]:
import tensorflow as tf

建立Tensorflow常数

In [2]:
ts_c = tf.constant(2, name = 'ts_c')

2 设置此常数为2

name = 'ts_c' 设置常数名称为ts_c，此名称会显示在计算图上

查看Tensorflow常数

In [3]:
ts_c

<tf.Tensor 'ts_c:0' shape=() dtype=int32>

**tf.Tensor:** 代表这是Tensorflow张量

**shape=():** 代表这是零维的tensor，也就是数值

**dtype=int32:** 代表该张量数据类型是int32

建立Tensorflow变量

In [4]:
ts_x = tf.Variable(ts_c + 5, name='ts_x')

ts_c+5 设置此变量数值是ts_c+5

name='ts_x' 设置此变量名称为ts_c，此名称会显示在计算图上

查看Tensorflow变量

In [5]:
ts_x

执行结果显示这是一个Tensorflow变量，但是变量的值必须在执行计算图后才可以显示

# 执行计算图

建立计算图后，我们就可以执行计算图。但是在执行前必须先建立Session（会话），在Tensorflow中Session代表在客户端和执行设备之间建立连接。有了这个连接，就可以在设备中执行计算图，后续任何与设备之间的沟通都必须通过这个Session，并且可以读取执行后的结果。

建立Session

In [6]:
sess = tf.Session()

执行Tensorflow来初始化变量

我们必须使用下列指令来初始化所有的Tensorflow变量

In [7]:
init = tf.global_variables_initializer()
sess.run(init)

使用sess.run显示Tensorflow常数

我们用sess.run执行计算图，并且用print打印Tensorflow常数的执行结果

In [9]:
print('ts_c=', sess.run(ts_c))

ts_c= 2


用同样的方法查看Tensorflow变量

In [10]:
print('ts_x=', sess.run(ts_x))

ts_x= 7


使用.eval()方法显示Tensorflow常数和Tensorflow变量

In [11]:
print('ts_c=', ts_c.eval(session=sess))

ts_c= 2


In [12]:
print('ts_x=', ts_x.eval(session=sess))

ts_x= 7


关闭Tensorflow Session

In [13]:
sess.close()

将以上代码一起执行

In [14]:
import tensorflow as tf
ts_c = tf.constant(2, name='ts_c')
ts_x = tf.Variable(ts_c + 5, name='ts_x')

sess = tf.Session()
init = tf.global_variables_initializer()
sess.run(init)
print('ts_c=', sess.run(ts_c))
print('ts_x=', sess.run(ts_x))
sess.close()

ts_c= 2
ts_x= 7


with语句打开Session并且自动关闭

在前面建立Session时，我们必须使用sess.close()关闭Session，这种做法可能有以下问题

（1）可能忘记关闭Session

（2）当程序执行发生异常时，可能导致没有关闭Session

为了解决此问题，我们可以使用with语句：

with后面的关键词是建立的命令tf.Session()，as关键词后面是Session的变量sess

在with程序块中可以使用sess变量与设备沟通，离开with程序就自动关闭Session

In [20]:
import tensorflow as tf
a = tf.constant(2, name='a')
x = tf.Variable(a + 5, name='x')
with tf.Session() as sess:
    init = tf.global_variables_initializer()
    sess.run(init)
    print('a=', sess.run(a))
    print('x=', sess.run(x))

a= 2
x= 7


# Tensorflow placeholder

在前面的例子中，我们是在建立计算图阶段设置好了常数和变量。使用placeholder，我们可以在执行计算图阶段再来设置数值

建立计算图

以下代码建立两个placeholder，分别是width（宽）与height（高），然后使用tf.multiply将width与height相乘，相乘的结果是area（面积）

In [21]:
width = tf.placeholder('int32')
height = tf.placeholder('int32')
area = tf.multiply(width, height)

执行计算图

In [22]:
with tf.Session() as sess:
    init = tf.global_variables_initializer()
    sess.run(init)
    print('area=', sess.run(area, feed_dict={width: 6, height: 8}))

area= 48


# Tensorflow数值运算方法介绍

常见的Tensorflow数值运算

tf.add(x, y, name = None) 加法

tf.subtract(x, y, name = None) 减法

tf.multiply(x, y, name = None) 乘法

tf.divide(x, y, name = None) 除法

tf.mod(x, y, name = None) 取余

tf.sqrt(x, name = None) 平方

tf.abs(x, name = None) 绝对值

name用于设置此运算的名称，详细的数值运算在http://www.tensorFlow.org/api_docs/python/math_ops/

这样的数值运算方法使得Tensorflow具备了跨平台的能力

# TensorBoard

Tensorflow提供了TensorBoard，让我们可以以可视化的方式查看所建立的计算图。

建立Tensorflow Variable变量

In [1]:
import tensorflow as tf
width = tf.placeholder('int32', name = 'width')
height = tf.placeholder('int32', name = 'height')
area = tf.multiply(width, height, name='area')

with tf.Session() as sess:
    init = tf.global_variables_initializer()
    sess.run(init)
    print('area=', sess.run(area, feed_dict={width: 6, height: 8}))

area= 48


将要显示在TensorBoard的数据写入log文件

In [2]:
tf.summary.merge_all() #将所有要显示在TensorBoard中的数据整合
train_writer = tf.summary.FileWriter('log/area', sess.graph)
#将所有要显示在TensorBoard中的数据写入log文件，log文件会保存在当前程序执行目录下的log/area子目录中

# 建立一维和二维张量

建立一维张量

In [26]:
ts_X = tf.Variable([0.4, 0.2, 0.4])

with tf.Session() as sess:
    init = tf.global_variables_initializer()
    sess.run(init)
    X = sess.run(ts_X)
    print(X)

[0.4 0.2 0.4]


上面建立的是一维张量，一共有三个数值

查看一维张量形状

In [27]:
print(X.shape)

(3,)


建立二维张量

In [28]:
ts_X = tf.Variable([[0.4, 0.2, 0.4]])

with tf.Session() as sess:
    init = tf.global_variables_initializer()
    sess.run(init)
    X = sess.run(ts_X)
    print(X)

[[0.4 0.2 0.4]]


查看二维张量形状

In [29]:
print(X.shape)

(1, 3)


第一维只有一项数据，所以是1；第二维每一项有三个数值，所以是3

再次建立二维张量

In [30]:
W = tf.Variable([[-0.5, -0.2], [-0.3, 0.4], [-0.5, 0.2]])

with tf.Session() as sess:
    init = tf.global_variables_initializer()
    sess.run(init)
    W_array = sess.run(W)
    print(W_array)

[[-0.5 -0.2]
 [-0.3  0.4]
 [-0.5  0.2]]


查看新的二维张量的形状

In [31]:
print(W_array.shape)

(3, 2)


第一维只有三项数据，所以是3，第二维，每一项数据有两个数值，所以是2

# 矩阵的基本运算

矩阵乘法

Tensorflow提供的tf.matmul()的方法。进行矩阵乘法时，可以按照如下步骤

$\bullet$ 建立计算图，先建立Tensorflow变量X和W，都是二维张量（矩阵），使用tf.matmul()进行矩阵的相乘得到变量XW

$\bullet$ 使用sess.run(XW)执行计算图，并使用print显示结果

In [38]:
X = tf.Variable([[1., 1., 1.]]) #注意这里必须输入浮点数，不能是整数，否则无法计算

W = tf.Variable([[-0.5, -0.2], 
                 [-0.3, 0.4], 
                 [-0.5, 0.2]])

XW = tf.matmul(X, W)

with tf.Session() as sess:
    init = tf.global_variables_initializer()
    sess.run(init)
    print(sess.run(XW))

[[-1.3  0.4]]


矩阵加法

在Tensorflow中，矩阵加法直接使用加号即可

In [39]:
b = tf.Variable([[0.1, 0.2]])
XW = tf.Variable([[-1.3, 0.4]])

Sum = XW + b

with tf.Session() as sess:
    init = tf.global_variables_initializer()
    sess.run(init)
    print(sess.run(Sum))

[[-1.1999999  0.6      ]]


Tensorflow中矩阵运算是浮点运算，所以是近似值，和真实值会有一点点误差