# 以矩阵运算仿真神经网络

Tensorflow张量运算仿真神经网络

In [2]:
import tensorflow as tf
X = tf.Variable([[0.4, 0.2, 0.4]])
W = tf.Variable([[-0.5, -0.2],
                [-0.3, 0.4],
                [-0.5, 0.2]])
b = tf.Variable([[0.1, 0.2]])
XWb = tf.matmul(X, W) + b
y = tf.nn.relu(XWb)
with tf.Session() as sess:
    init = tf.global_variables_initializer()
    sess.run(init)
    print('XWb:'); print(sess.run(XWb))
    print('y'); print(sess.run(y))

XWb:
[[-0.35999998  0.28      ]]
y
[[0.   0.28]]


把relu函数换成sigmoid函数

In [3]:
X = tf.Variable([[0.4, 0.2, 0.4]])
W = tf.Variable([[-0.5, -0.2],
                [-0.3, 0.4],
                [-0.5, 0.2]])
b = tf.Variable([[0.1, 0.2]])
XWb = tf.matmul(X, W) + b
y = tf.nn.sigmoid(XWb)
with tf.Session() as sess:
    init = tf.global_variables_initializer()
    sess.run(init)
    print('XWb:'); print(sess.run(XWb))
    print('y'); print(sess.run(y))

XWb:
[[-0.35999998  0.28      ]]
y
[[0.41095957 0.5695462 ]]


用正态分布随机数生成权重和偏置的初始值

In [4]:
X = tf.Variable([[0.4, 0.2, 0.4]])
W = tf.Variable(tf.random_normal([3, 2]))
b = tf.Variable(tf.random_normal([1,2]))
XWb = tf.matmul(X, W) + b
y = tf.nn.relu(XWb)
with tf.Session() as sess:
    init = tf.global_variables_initializer()
    sess.run(init)
    print('XWb:'); print(sess.run(XWb))
    print('y'); print(sess.run(y))

XWb:
[[ 1.0973048  -0.07433489]]
y
[[1.0973048 0.       ]]


执行一次sess.run()可以取的三个Tensorflow变量

In [6]:
X = tf.Variable([[0.4, 0.2, 0.4]])
W = tf.Variable(tf.random_normal([3, 2]))
b = tf.Variable(tf.random_normal([1,2]))
XWb = tf.matmul(X, W) + b
y = tf.nn.relu(XWb)
with tf.Session() as sess:
    init = tf.global_variables_initializer()
    sess.run(init)
    (_b, _W, _y) = sess.run((b, W, y))
    print('b:')
    print(_b)
    print('W')
    print(_W)
    print('y')
    print(_y)

b:
[[-1.1247821  2.0273416]]
W
[[ 0.48953384 -0.6280775 ]
 [-2.2979689  -0.31554702]
 [-0.54036593 -1.0841802 ]]
y
[[0.        1.2793291]]


# 以placeholder传入X值

以placeholder传入1 × 3的二维数组

In [7]:
import numpy as np
W = tf.Variable(tf.random_normal([3, 2]))
b = tf.Variable(tf.random_normal([1, 2]))
X = tf.placeholder('float', [None, 3])
y = tf.nn.relu(tf.matmul(X, W) + b)
with tf.Session() as sess:
    init = tf.global_variables_initializer()
    sess.run(init)
    X_array = np.array([[0.4, 0.2, 0.4]])
    (_b, _W, _X, _y) = sess.run((b, W, X, y), feed_dict={X: X_array})
    print('b:');print(_b);
    print('W:');print(_W);
    print('X:');print(_X);
    print('y:');print(_y)

b:
[[-0.78177404  1.1379212 ]]
W:
[[-0.83753026  0.20257422]
 [-0.41789827 -0.5366737 ]
 [ 0.20537344 -0.36410642]]
X:
[[0.4 0.2 0.4]]
y:
[[0.        0.9659736]]


以placeholder传入3 × 3二维数组

In [8]:
W = tf.Variable(tf.random_normal([3, 2]))
b = tf.Variable(tf.random_normal([1, 2]))
X = tf.placeholder('float', [None, 3])
y = tf.nn.relu(tf.matmul(X, W) + b)
with tf.Session() as sess:
    init = tf.global_variables_initializer()
    sess.run(init)
    X_array = np.array([[0.4, 0.2, 0.4],
                       [0.3, 0.4, 0.5],
                       [0.3, -0.4, 0.5]])
    (_b, _W, _X, _y) = sess.run((b, W, X, y), feed_dict={X: X_array})
    print('b:');print(_b);
    print('W:');print(_W);
    print('X:');print(_X);
    print('y:');print(_y)

b:
[[ 0.26287666 -1.9514232 ]]
W:
[[-0.06532464  1.6326824 ]
 [ 0.56742567 -0.24778531]
 [ 0.25008273  0.34466177]]
X:
[[ 0.4  0.2  0.4]
 [ 0.3  0.4  0.5]
 [ 0.3 -0.4  0.5]]
y:
[[0.45026505 0.        ]
 [0.5952909  0.        ]
 [0.14135036 0.        ]]


# 创建layer函数以矩阵运算仿真神经网络

layer函数

我们下面创建layer函数，功能是建立两层的神经网络

In [10]:
def layer(output_dim, input_dim, inputs, activation = None):
    #用正态随机数初始化权重和偏置
    W = tf.Variable(tf.random_normal([input_dim, output_dim]))
    b = tf.Variable(tf.random_normal([1, output_dim]))
    #建立矩阵表达式XWb = (input * W) + b
    XWb = tf.matmul(inputs, W) + b
    #计算激活函数值
    if activation is None:
        outputs = XWb 
    else:
        outputs = activation(XWb)
    #返回已经建立的神经网络层
    return outputs

**输入参数说明**

output_dim 输出神经元数量

input_dim 输入神经元数量

inputs 输入的二维数组placeholdler

activation 输入的激活函数，默认是None

使用layer函数建立三层类神经网络层

我们下面用layer函数建立三层类神经网络，输入层有4个神经元，隐藏层有3个神经元，输出层有两个神经元

In [12]:
X = tf.placeholder('float', [None, 4]) #第一维设置为None，因为项数不固定
h = layer(output_dim=3, input_dim=4, inputs=X, activation=tf.nn.relu)#建立隐藏层h，激活函数为relu
y = layer(output_dim=2, input_dim=3, inputs=h)#建立输出层y
with tf.Session() as sess:
    init = tf.global_variables_initializer()
    sess.run(init)
    X_array = np.array([[0.4, 0.2, 0.4, 0.5]])
    (layer_X, layer_h, layer_y) = sess.run((X, h, y), feed_dict={X: X_array})
    print('input Layer X:');print(layer_X)
    print('hidden Layer h:');print(layer_h)
    print('output Layer y:');print(layer_y)

input Layer X:
[[0.4 0.2 0.4 0.5]]
hidden Layer h:
[[0.         2.088194   0.51277566]]
output Layer y:
[[0.96104944 0.8929039 ]]


建立layer_debug函数显示权重与偏差

layer_debug函数与layer函数类似，除了返回outputs外，还返回W和b

In [13]:
def layer(output_dim, input_dim, inputs, activation = None):
    #用正态随机数初始化权重和偏置
    W = tf.Variable(tf.random_normal([input_dim, output_dim]))
    b = tf.Variable(tf.random_normal([1, output_dim]))
    #建立矩阵表达式XWb = (input * W) + b
    XWb = tf.matmul(inputs, W) + b
    #计算激活函数值
    if activation is None:
        outputs = XWb 
    else:
        outputs = activation(XWb)
    #返回已经建立的神经网络层
    return outputs, W, b

使用layer_debug函数建立三层类神经网络并且显示W和b

In [14]:
X = tf.placeholder('float', [None, 4]) #第一维设置为None，因为项数不固定
h, W1, b1 = layer(output_dim=3, input_dim=4, inputs=X, activation=tf.nn.relu)#建立隐藏层h，激活函数为relu
y, W2, b2 = layer(output_dim=2, input_dim=3, inputs=h)#建立输出层y
with tf.Session() as sess:
    init = tf.global_variables_initializer()
    sess.run(init)
    X_array = np.array([[0.4, 0.2, 0.4, 0.5]])
    (layer_X, layer_h, layer_y, W1, b1, W2, b2) = sess.run((X, h, y, W1, b1, W2, b2), feed_dict={X: X_array})
    print('input Layer X:');print(layer_X)
    print('W1:');print(W1)
    print('b1:');print(b1)
    print('hidden Layer h:');print(layer_h)
    print('W2:');print(W2)
    print('b2:');print(b2)
    print('output Layer y:');print(layer_y)

input Layer X:
[[0.4 0.2 0.4 0.5]]
W1:
[[ 0.93133837  0.5364994  -0.24151532]
 [-0.13198993 -0.39711076 -0.07884934]
 [-0.6056461   1.079882   -1.3018585 ]
 [-0.24656637  1.3235065  -0.70020866]]
b1:
[[ 0.02427516  0.96883565 -0.42784122]]
hidden Layer h:
[[0.00487092 2.1977193  0.        ]]
W2:
[[ 0.03648379  1.2604636 ]
 [-0.04330066 -0.08184922]
 [ 0.9764039  -0.12139777]]
b2:
[[-0.8583216 -1.5012769]]
output Layer y:
[[-0.9533066 -1.6750188]]
